import "./globals.css";
import Navbars from "@/components/navbars/Navbars";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbars />
        {children}
      </body>
    </html>
  );
}
